const seatData = [
    { id: 1, seat: "1", reserved: false },
    { id: 2, seat: "2", reserved: false },
    { id: 3, seat: "3", reserved: false },
    { id: 4, seat: "4", reserved: false },
    { id: 5, seat: "5", reserved: false },
    { id: 6, seat: "6", reserved: false },
    { id: 7, seat: "7", reserved: false },
    { id: 8, seat: "8", reserved: false },
    { id: 9, seat: "9", reserved: false },
    { id: 10, seat: "10", reserved: false },
    { id: 11, seat: "11", reserved: false },
    { id: 12, seat: "12", reserved: false },
    { id: 13, seat: "13", reserved: false },
    { id: 14, seat: "14", reserved: false },
    { id: 15, seat: "15", reserved: false },
    { id: 16, seat: "16", reserved: false },
    { id: 17, seat: "17", reserved: false },
    { id: 18, seat: "18", reserved: false },
    { id: 19, seat: "19", reserved: false },
    { id: 20, seat: "20", reserved: false },
    { id: 21, seat: "21", reserved: false },
    { id: 22, seat: "22", reserved: false },
    { id: 23, seat: "23", reserved: false },
    { id: 24, seat: "24", reserved: false },
    { id: 25, seat: "25", reserved: false },
    { id: 26, seat: "26", reserved: false },
    { id: 27, seat: "27", reserved: false },
    { id: 28, seat: "28", reserved: false },
    { id: 29, seat: "29", reserved: false },
    { id: 30, seat: "30", reserved: false },
    { id: 31, seat: "31", reserved: false },
    { id: 32, seat: "32", reserved: false },
    { id: 33, seat: "33", reserved: false },
    { id: 34, seat: "34", reserved: false },
    { id: 35, seat: "35", reserved: false },
    { id: 36, seat: "36", reserved: false },
    { id: 37, seat: "37", reserved: false },
    { id: 38, seat: "38", reserved: false },
    { id: 39, seat: "39", reserved: false },
    { id: 40, seat: "40", reserved: false },
];

export default seatData;
